//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAssistance.COMMONS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COAssistance.COMMONS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesreća.
        /// </summary>
        public static string Accident {
            get {
                return ResourceManager.GetString("Accident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Račun aktivan.
        /// </summary>
        public static string AccountActive {
            get {
                return ResourceManager.GetString("AccountActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviraj.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivna od.
        /// </summary>
        public static string ActiveFrom {
            get {
                return ResourceManager.GetString("ActiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivna do.
        /// </summary>
        public static string ActiveTo {
            get {
                return ResourceManager.GetString("ActiveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kompaniju.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj policu.
        /// </summary>
        public static string AddPolicy {
            get {
                return ResourceManager.GetString("AddPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi zapis.
        /// </summary>
        public static string AddRecord {
            get {
                return ResourceManager.GetString("AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj stanicu.
        /// </summary>
        public static string AddStation {
            get {
                return ResourceManager.GetString("AddStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracija.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergija.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška u aplikaciji.
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do neočekivane greške u aplikaciji. Pokušajte ponovno kasnije..
        /// </summary>
        public static string ApplicationErrorText {
            get {
                return ResourceManager.GetString("ApplicationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dolaska.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme dolaska.
        /// </summary>
        public static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne postavke.
        /// </summary>
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krvna grupa.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granični prijelaz.
        /// </summary>
        public static string BorderCrossings {
            get {
                return ResourceManager.GetString("BorderCrossings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL fotografije kamere.
        /// </summary>
        public static string CameraPhotoURL {
            get {
                return ResourceManager.GetString("CameraPhotoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamere.
        /// </summary>
        public static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve prethodno sačuvane stavke su izbrisane..
        /// </summary>
        public static string CancelSuccess {
            get {
                return ResourceManager.GetString("CancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj kartice.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija I.
        /// </summary>
        public static string CategoryI {
            get {
                return ResourceManager.GetString("CategoryI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija II.
        /// </summary>
        public static string CategoryII {
            get {
                return ResourceManager.GetString("CategoryII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija III.
        /// </summary>
        public static string CategoryIII {
            get {
                return ResourceManager.GetString("CategoryIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija IV.
        /// </summary>
        public static string CategoryIV {
            get {
                return ResourceManager.GetString("CategoryIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni lozinku.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni status.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite kategoriju.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite kompaniju.
        /// </summary>
        public static string ChooseCompany {
            get {
                return ResourceManager.GetString("ChooseCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite valutu.
        /// </summary>
        public static string ChooseCurrency {
            get {
                return ResourceManager.GetString("ChooseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite ulaz.
        /// </summary>
        public static string ChooseEntrance {
            get {
                return ResourceManager.GetString("ChooseEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite izlaz.
        /// </summary>
        public static string ChooseExit {
            get {
                return ResourceManager.GetString("ChooseExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi datoteku.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite vrstu goriva.
        /// </summary>
        public static string ChooseFuelType {
            get {
                return ResourceManager.GetString("ChooseFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite autoput.
        /// </summary>
        public static string ChooseHighway {
            get {
                return ResourceManager.GetString("ChooseHighway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite vrstu stanja na putu.
        /// </summary>
        public static string ChooseRoadConditionType {
            get {
                return ResourceManager.GetString("ChooseRoadConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kronične bolesti.
        /// </summary>
        public static string ChronicDiseases {
            get {
                return ResourceManager.GetString("ChronicDiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikni za detalje.
        /// </summary>
        public static string ClickForDetails {
            get {
                return ResourceManager.GetString("ClickForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijent.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povijest logiranja.
        /// </summary>
        public static string ClientLoginData {
            get {
                return ResourceManager.GetString("ClientLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijenti.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijent ima postavljen &quot;{0}&quot; jezik..
        /// </summary>
        public static string ClientsLanguage {
            get {
                return ResourceManager.GetString("ClientsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhronizacija klijenata.
        /// </summary>
        public static string ClientSync {
            get {
                return ResourceManager.GetString("ClientSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompanija.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završeno.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni ?.
        /// </summary>
        public static string ConfirmationNote {
            get {
                return ResourceManager.GetString("ConfirmationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovljena lozinka.
        /// </summary>
        public static string ConfirmedPassword {
            get {
                return ResourceManager.GetString("ConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdite novu lozinku.
        /// </summary>
        public static string ConfirmedPasswordNote {
            get {
                return ResourceManager.GetString("ConfirmedPasswordNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi odabir.
        /// </summary>
        public static string ConfirmSelection {
            get {
                return ResourceManager.GetString("ConfirmSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt osoba.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadržaj.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traženi sadržaj nije pronađen. Vratite se na kontrolnu ploču i pokušajte ponovno..
        /// </summary>
        public static string ContentNotFound {
            get {
                return ResourceManager.GetString("ContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kreiranja.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutno aktivno.
        /// </summary>
        public static string CurrentlyActive {
            get {
                return ResourceManager.GetString("CurrentlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolna ploča.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom učitavanja podataka. Molimo pokušajte kasnije..
        /// </summary>
        public static string DataLoadError {
            get {
                return ResourceManager.GetString("DataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani zapis više ne postoji..
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani datum mora biti ispred današnjeg datuma..
        /// </summary>
        public static string DateConflict {
            get {
                return ResourceManager.GetString("DateConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum nije postavljen.
        /// </summary>
        public static string DateNotSet {
            get {
                return ResourceManager.GetString("DateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite datum ili označite predefinisano trajanje police..
        /// </summary>
        public static string DateOrPredefined {
            get {
                return ResourceManager.GetString("DateOrPredefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dan.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dana.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviraj.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li sigurno želite izbrisati odabrani zapis ?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbrisano.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje zapisa.
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terapija.
        /// </summary>
        public static string Diagnose {
            get {
                return ResourceManager.GetString("Diagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriranje zapisa.
        /// </summary>
        public static string EditRecord {
            get {
                return ResourceManager.GetString("EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresa nije u validnom formatu..
        /// </summary>
        public static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon za hitne slučaje.
        /// </summary>
        public static string EmergencyContactPhoneNumber {
            get {
                return ResourceManager.GetString("EmergencyContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaz.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocesta ulaza.
        /// </summary>
        public static string EntranceHighway {
            get {
                return ResourceManager.GetString("EntranceHighway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplatna kućica - ulaz.
        /// </summary>
        public static string EntranceTollbooth {
            get {
                return ResourceManager.GetString("EntranceTollbooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora sadržavati minimalno 6 karaktera..
        /// </summary>
        public static string ErrorUsernameLength {
            get {
                return ResourceManager.GetString("ErrorUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocesta izlaza.
        /// </summary>
        public static string ExitHighway {
            get {
                return ResourceManager.GetString("ExitHighway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplatna kućica - Izlaz.
        /// </summary>
        public static string ExitTollbooth {
            get {
                return ResourceManager.GetString("ExitTollbooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajektni promet.
        /// </summary>
        public static string FerryTrafic {
            get {
                return ResourceManager.GetString("FerryTrafic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir dadoteke je obavezan..
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime i prezime.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompanije.
        /// </summary>
        public static string GasCompanies {
            get {
                return ResourceManager.GetString("GasCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzinske pumpe.
        /// </summary>
        public static string GasStations {
            get {
                return ResourceManager.GetString("GasStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravstveni problemi.
        /// </summary>
        public static string HealthProblems {
            get {
                return ResourceManager.GetString("HealthProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je poslao zahtjev za pomoć..
        /// </summary>
        public static string HelpRequestNotificationMessage {
            get {
                return ResourceManager.GetString("HelpRequestNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjevi za pomoć.
        /// </summary>
        public static string HelpRequests {
            get {
                return ResourceManager.GetString("HelpRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoput.
        /// </summary>
        public static string Highway {
            get {
                return ResourceManager.GetString("Highway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoputevi.
        /// </summary>
        public static string Highways {
            get {
                return ResourceManager.GetString("Highways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U obzir će se uzeti samo kategorije sa postavljenom cijenom..
        /// </summary>
        public static string HigwayRoutePricesNote {
            get {
                return ResourceManager.GetString("HigwayRoutePricesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povijest kritičnih bolesti.
        /// </summary>
        public static string HistoryOfCriticalIllness {
            get {
                return ResourceManager.GetString("HistoryOfCriticalIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neaktivan.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrukcije.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj police.
        /// </summary>
        public static string InsurancePolicyNumber {
            get {
                return ResourceManager.GetString("InsurancePolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešno korisničko ime ili lozinka..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneseni URL nije validan..
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavke.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj stavki.
        /// </summary>
        public static string ItemsNumber {
            get {
                return ResourceManager.GetString("ItemsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posljednji put logiran.
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posljednji klijenti.
        /// </summary>
        public static string LatestClients {
            get {
                return ResourceManager.GetString("LatestClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografska širina.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dužina.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId nije prisutan ili nije validan. Akciju logiranja nije moguće nastaviti..
        /// </summary>
        public static string LoginClientIdMissingOrInvalid {
            get {
                return ResourceManager.GetString("LoginClientIdMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko ne želite izmijeniti postojeći logo, kliknite dugme Potvrdi. U suprotnom, odaberite novu fotografiju i potvrdite odabir..
        /// </summary>
        public static string LogoInfo {
            get {
                return ResourceManager.GetString("LogoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografska dužina.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Održavanje.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Održavanje.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj uloge.
        /// </summary>
        public static string ManageRoles {
            get {
                return ResourceManager.GetString("ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite lokaciju na mapi kako bi se automatski popunila polja Geografska širina i dužina. Ukoliko se polja ne popune, odaberite drugo polje ili podatke unesite ručno..
        /// </summary>
        public static string MapCoordinatesInputInfo {
            get {
                return ResourceManager.GetString("MapCoordinatesInputInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova stavka.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naprijed.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema pronađenih stavki.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate novih notifikacija..
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtjev trenutno nema odgovora..
        /// </summary>
        public static string NoResponses {
            get {
                return ResourceManager.GetString("NoResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema pronađenih zapisa..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema pronađenih rezultata pretrage..
        /// </summary>
        public static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifikacije.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imate {0} notifikacija.  .
        /// </summary>
        public static string NotificationsNumberInfo {
            get {
                return ResourceManager.GetString("NotificationsNumberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije postavljeno.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Client Id nije aktivan..
        /// </summary>
        public static string OAuthClientIdInactive {
            get {
                return ResourceManager.GetString("OAuthClientIdInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijentska aplikacija.
        /// </summary>
        public static string OAuthClientName {
            get {
                return ResourceManager.GetString("OAuthClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara lozinka.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redni broj.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostalo.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovljena lozinka.
        /// </summary>
        public static string PasswordConfirmed {
            get {
                return ResourceManager.GetString("PasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dužina lozinke.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesene lozinke se ne podudaraju..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena lozinke.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste ažurirali lozinku..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati minimalno 6 karaktera i 1 specijalni karakter..
        /// </summary>
        public static string PasswordStrengthInfo {
            get {
                return ResourceManager.GetString("PasswordStrengthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena lozinka ne zadovoljava unesene uvjete..
        /// </summary>
        public static string PasswordWeakInput {
            get {
                return ResourceManager.GetString("PasswordWeakInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polica aktivna od.
        /// </summary>
        public static string PolicyActiveFrom {
            get {
                return ResourceManager.GetString("PolicyActiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polica aktivna do.
        /// </summary>
        public static string PolicyActiveTo {
            get {
                return ResourceManager.GetString("PolicyActiveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum isteka police mora biti ispred današnjeg datuma..
        /// </summary>
        public static string PolicyDateConflict {
            get {
                return ResourceManager.GetString("PolicyDateConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje police.
        /// </summary>
        public static string PolicyDuration {
            get {
                return ResourceManager.GetString("PolicyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje police izraženo u danima.
        /// </summary>
        public static string PolicyDurationNote {
            get {
                return ResourceManager.GetString("PolicyDurationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polica istekla.
        /// </summary>
        public static string PolicyExpired {
            get {
                return ResourceManager.GetString("PolicyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite dužinu lozinke i broj specijalnih karaktera.
        ///Predefinisane vrijednosti su {0} za dužinu i {1} za broj specijalnih karaktera..
        /// </summary>
        public static string PredefinedPasswordPolicy {
            get {
                return ResourceManager.GetString("PredefinedPasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefinisano trajanje police je {0} dana..
        /// </summary>
        public static string PredefinedPolicyDuration {
            get {
                return ResourceManager.GetString("PredefinedPolicyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijene.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno jedna cijena kategorije mora biti postavljena..
        /// </summary>
        public static string PricesRequired {
            get {
                return ResourceManager.GetString("PricesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnički profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Željeznički promet.
        /// </summary>
        public static string RailwayTraffic {
            get {
                return ResourceManager.GetString("RailwayTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivacija zapisa.
        /// </summary>
        public static string RecordActivation {
            get {
                return ResourceManager.GetString("RecordActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani zapis je ponovno aktivan..
        /// </summary>
        public static string RecordActive {
            get {
                return ResourceManager.GetString("RecordActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali novi zapis..
        /// </summary>
        public static string RecordAddSuccess {
            get {
                return ResourceManager.GetString("RecordAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izbrisali odabrani zapis..
        /// </summary>
        public static string RecordDeleteSuccess {
            get {
                return ResourceManager.GetString("RecordDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve izmjene su uspješno sačuvane..
        /// </summary>
        public static string RecordEditSuccess {
            get {
                return ResourceManager.GetString("RecordEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani zapis više nije aktivan..
        /// </summary>
        public static string RecordInactive {
            get {
                return ResourceManager.GetString("RecordInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani zapis je uspješno vraćen..
        /// </summary>
        public static string RecordRestoreSuccess {
            get {
                return ResourceManager.GetString("RecordRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovani.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamti me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje zahtjeva.
        /// </summary>
        public static string RequestState {
            get {
                return ResourceManager.GetString("RequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovo polje je obavezno..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrati.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukoliko zapis označite kao aktivan, trenutno aktivan zapis će biti deaktiviran..
        /// </summary>
        public static string RoadConditionActivationNote {
            get {
                return ResourceManager.GetString("RoadConditionActivationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje na putevima.
        /// </summary>
        public static string RoadConditions {
            get {
                return ResourceManager.GetString("RoadConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta stanja na putu .
        /// </summary>
        public static string RoadConditionType {
            get {
                return ResourceManager.GetString("RoadConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radovi na putu.
        /// </summary>
        public static string RoadWorks {
            get {
                return ResourceManager.GetString("RoadWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno jedna uloga mora biti odabrana..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloge.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rute.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identičan zapis već postoji..
        /// </summary>
        public static string RowConflict {
            get {
                return ResourceManager.GetString("RowConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst pretrage.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vidi sve.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži izbrisano.
        /// </summary>
        public static string ShowDeleted {
            get {
                return ResourceManager.GetString("ShowDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori sa Google mapama.
        /// </summary>
        public static string ShowOnGoogleMaps {
            get {
                return ResourceManager.GetString("ShowOnGoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži na mapi.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj specijalnih karaktera.
        /// </summary>
        public static string SpecialCharacters {
            get {
                return ResourceManager.GetString("SpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoblje.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traži.
        /// </summary>
        public static string SubmitSearch {
            get {
                return ResourceManager.GetString("SubmitSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ističe.
        /// </summary>
        public static string TokenExpiresTime {
            get {
                return ResourceManager.GetString("TokenExpiresTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izdan.
        /// </summary>
        public static string TokenIssuedTime {
            get {
                return ResourceManager.GetString("TokenIssuedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplatna kućica.
        /// </summary>
        public static string Tollbooth {
            get {
                return ResourceManager.GetString("Tollbooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulazna i izlazna kućica ne mogu biti iste..
        /// </summary>
        public static string TollboothConflict {
            get {
                return ResourceManager.GetString("TollboothConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplatne kućice.
        /// </summary>
        public static string Tollbooths {
            get {
                return ResourceManager.GetString("Tollbooths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protok prometa.
        /// </summary>
        public static string TrafficFlow {
            get {
                return ResourceManager.GetString("TrafficFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prometna prognoza.
        /// </summary>
        public static string TrafficForecast {
            get {
                return ResourceManager.GetString("TrafficForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neregistrovani.
        /// </summary>
        public static string Unregistered {
            get {
                return ResourceManager.GetString("Unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string UrlLink {
            get {
                return ResourceManager.GetString("UrlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koristi predefinisano trajanje police?.
        /// </summary>
        public static string UseDefaultPolicyDuration {
            get {
                return ResourceManager.GetString("UseDefaultPolicyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničke grupe.
        /// </summary>
        public static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste autorizovani da pristupite ovoj aplikaciji..
        /// </summary>
        public static string UserNotAuthorizedToAccessResource {
            get {
                return ResourceManager.GetString("UserNotAuthorizedToAccessResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka je uspješno poslana na korisničku e-mail adresu..
        /// </summary>
        public static string UserPasswordResetSuccess {
            get {
                return ResourceManager.GetString("UserPasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validan od.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validan do.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Važi do.
        /// </summary>
        public static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj šasije.
        /// </summary>
        public static string VehicleChassis {
            get {
                return ResourceManager.GetString("VehicleChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracijske oznake.
        /// </summary>
        public static string VehicleLicencePlateNumber {
            get {
                return ResourceManager.GetString("VehicleLicencePlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzija.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži sve.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web adresa.
        /// </summary>
        public static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
